Rrs 53 add basic property details to db
CM20314-Group-7/rental-review pull request #21
Opened 2024-02-19 13:12 UTC by euand1818

2024-02-19 13:41 UTC, LukeHosk requested changes
Move './supabase/migrations/supabase.types.ts' to './supabase.types.ts'

2024-02-19 14:55 UTC, euand1818 reviewed
Should be done now.

2024-02-20 08:14 UTC, LukeHosk commented
Your type tests are failing because this branch is behind development and is missing other changes to the database. So the types in this branch are different to this branch merged with development

you need to either:
- checkout this PR and run the typegen directly on it
- merge development into this branch. check it still works as intended & does not conflict, then run typegen ( preferred )

2024-02-20 08:26 UTC, LukeHosk requested changes

2024-02-20 08:26 UTC, LukeHosk commented on supabase/migrations/20240205224252_init_db.sql
You also should not be changing the existing migrations. Rather creating new ones.

Migrations should represent a linear history, and a server should be able to say 'i have migrations 1, 2, and 3, here is a new migration 4, ill apply that and now I'm up to date' if you change 1, then none of those changes will be propagated to existing deployments, potentially breaking the whole database once other new pieces are added on top that expect a different bottom.

We could probably get away with it here given that this migration has not yet been pushed to production and we have no other deployments, however it is also bad practice to change what other developers can expect out the db, and a good practice to get in the habit of doing it in a way that won't break anything.

The only times we should realistically be changing existing migrations are:
- In your own, not yet merged branch
- If the migration is broken
- In dedicated migration adjustments ( e.g. compressing a sprint's various changes before pushing to prod or realising that we dropped a column we want to keep and should remove that statement before it can delete data ) that are explicitly checking for conflicts / existing deployments

2024-02-20 18:20 UTC, LukeHosk commented
Looks like the changes to the database cause issues for some of the server actions.

@euand1818  Would you like to look at updating them or should I?

2024-02-21 16:07 UTC, euand1818 commented
I'll have a shot and then come back if I get stuck on anything.

2024-02-21 16:33 UTC, closed without merging