RRS-63 display owning landlords on property page
CM20314-Group-7/rental-review pull request #45
Opened 2024-02-26 21:55 UTC by OttoChu

Added unit test for the property page. (Only for landlord name)

Also, set up some data in the seed file for future tests on reviews.

2024-02-26 22:56 UTC, LukeHosk requested changes

2024-02-26 22:56 UTC, LukeHosk commented on playwright-tests/properties-page-tests.spec.ts
> +
**Optional**: consider setting up a helper object for properties like I did for the users

2024-02-26 22:56 UTC, LukeHosk commented on playwright-tests/properties-page-tests.spec.ts
> +});
**Optional**: Consider separating into grouped tests to allow individual parts to pass or fail separately e.g.

```typescript
test.describe('details shown correctly for existing property' ...
    test('property address shown'...

    )

    test('current landlord shown'...

    )
)
```

2024-02-26 22:56 UTC, LukeHosk commented on app/properties/[id]/page.tsx
> +        .not('ended_at', 'is', null)
I'm pretty sure this change does the exact opposite of what we want

`ended_at` should be `null` when the ownership has not ended, and the user is the current landlord.

Unless I'm wrong and this does not work as expected, you want to leave this as it is, and add a separate fetch to check for ownerships where this field is not `null` to populate a list of past landlords.

Personally I would display the other landlords either in a dropdown or link it to a separate page/modal with the full breakdown of past owners with dates, but that's up to you.

2024-02-26 22:56 UTC, LukeHosk commented on app/properties/page.tsx
> +                <h1>Profile Page</h1>
Do we want to label the page as 'Profile Page' I would have thought the landlord's name is a more appropriate title.

if you look at say a youtube video, it wouldn't say 'video page' it just has the title of the video

This tilte is also on the property page not the landlord profile. Is this a mistake?

2024-02-26 22:56 UTC, LukeHosk commented on supabase/seed.sql
You seem to be using the same users as reviewers as we already have as landlords.

I would suggest using different users to avoid having landlords review their own properties

I'm also not sure whether all the additional tests you have detailed are supposed to be for the properties page or the landlord page. you should use the `Used For` column to list all tests that use that record, and the `Details` column to explain what data those tests expect.

It's also not clear in lines like `Must not have any property reviews ` whether you mean that that user must not have reviewed any properties, or whether that user must not have been reviewed on properties.

2024-02-26 23:44 UTC, OttoChu commented on supabase/seed.sql
Those were supposed to be for testing the average rating, but I thought I should add the relevant test in the other branch in the middle of making them. I don't want to lose the progress, so I just pushed it here.

2024-02-27 00:07 UTC, LukeHosk commented on supabase/seed.sql
`git stash`?

2024-02-27 00:12 UTC, OttoChu commented on supabase/seed.sql
Could do but I also needed some of the other parts

2024-02-27 00:13 UTC, LukeHosk requested changes

2024-02-27 00:13 UTC, LukeHosk commented on playwright-tests/properties-page-tests.spec.ts
> +  await expect(page.getByRole('main')).toContainText('1 Test Road');
You added the property address to your helper object, but aren't using it here.

If you are going to do it this way, I would expect this line to read
`await expect(page.getByRole('main')).toContainText(firstProperty.address);`

2024-02-27 00:14 UTC, LukeHosk commented on supabase/seed.sql
you should be able to stash only select hunks

2024-02-27 00:15 UTC, LukeHosk commented on supabase/seed.sql
or you can `ctrl + A` `ctrl + C`, clean it up, commit, `ctrl + A` `ctrl + V`

2024-02-27 00:17 UTC, LukeHosk commented on supabase/seed.sql
or even if you just add a little `TBD` in the `Used For` column to indicate that we have not yet decided/defined the tests

2024-02-27 00:17 UTC, LukeHosk commented on supabase/seed.sql
I just read those comments and have no clue what is going on, which indicates it's not ready to merge into a collaborative branch

2024-02-27 17:49 UTC, LukeHosk approved these changes

2024-02-27 17:55 UTC, merged